FROM node:24-slim

# Set working directory
WORKDIR /app

# Install dependencies first
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose server port
EXPOSE 5000

# Start server with hot-reload for TS
CMD ["npx", "nodemon", "--watch", "src", "--exec", "ts-node", "src/index.ts"]
