FROM node:24-slim

WORKDIR /app

# Copy package.json first and install deps
COPY package*.json ./
ENV NODE_ENV=development
RUN npm install

# Copy source
COPY . .

# Expose port
EXPOSE 5000

# Start server
CMD ["npm", "run", "dev"]
