# Stage 1: Build
FROM node:24-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Compile TS and fix aliases
RUN npx tsc && npx tsc-alias

# Stage 2: Production image
FROM node:24-slim

WORKDIR /app

COPY package*.json ./
RUN npm install --production

# Copy compiled JS from builder
COPY --from=builder /app/dist ./dist


EXPOSE 5000

CMD ["node", "dist/index.js"]
